/*
 * CombatGUI.java
 * 
 * 
 * Created on 03/11/2011, 7:03:14 PM
 */
package game.src.battleSim;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;

import game.src.entities.*;

import java.util.ArrayList;
/**
 * This Class handles the GUI and extends JFrame
 * 
 * it is very broken and full of legacy code and auto generated crap
 * 
 * TODO: completely rewrite it
 * 
 * @author Jason and Funkballs
 */
public class CombatGUI extends javax.swing.JFrame {
//private Player spartan101;
//private ArrayList<Enemy> enemies;
 // private ArrayList<Base> entities;
  private Battle battle;
    /** Creates new form RunSim */
    public CombatGUI(Battle battle) {
    	this.battle = battle;
    	
        /* Create and display the form */
        initComponents();
        setup();
        update();    
        setVisible(true);
        System.out.println("Battle Start");      
        //mainMenu.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        hpFeildPlayer = new javax.swing.JTextField();
        hpLabel = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        hpFeildEnemy = new javax.swing.JTextField();
        tpLabel = new javax.swing.JLabel();
        tpFeild = new javax.swing.JTextField();
        mainMenu = new javax.swing.JLayeredPane();
        basicAttack = new javax.swing.JButton();
        specialAttack = new javax.swing.JButton();
        specialMenu = new javax.swing.JLayeredPane();
        bBlade = new javax.swing.JButton();
        specialBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        test = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        hpFeildPlayer.setEditable(false);
        hpFeildPlayer.setText("10");

        hpLabel.setText("HP:");

        name.setText("Spartan101");

        jLabel1.setText("Grunt");

        hpFeildEnemy.setEditable(false);
        hpFeildEnemy.setText("10");

        tpLabel.setText("TP:");

        tpFeild.setEditable(false);
        tpFeild.setText("10");

        



        jLabel2.setText("HP:");

        test.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jSeparator1)
                            .addContainerGap())
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tpLabel, javax.swing.GroupLayout.Alignment.LEADING, 0, 1, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(hpLabel)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tpFeild, 0, 1, Short.MAX_VALUE)
                                .addComponent(hpFeildPlayer))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(test, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(67, 67, 67))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(556, 556, 556)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(hpFeildEnemy, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addContainerGap())
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(name)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(mainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(specialMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(276, 276, 276)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hpLabel)
                    .addComponent(hpFeildPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tpLabel)
                    .addComponent(tpFeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(test, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hpFeildEnemy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(specialMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainMenu))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//
//private void basicAttackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basicAttackActionPerformed
//  
//	//TODO: change attack handling
//	int i = Integer.parseInt(JOptionPane.showInputDialog("Which enemy?"));  
//	JOptionPane.showMessageDialog(null,"attacking now");
//	battle.attack(0,i);
//    //enemyAttack();
//}//GEN-LAST:event_basicAttackActionPerformed
//
//private void bBladeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBladeActionPerformed
//    specialMenu.setVisible(false);
//    mainMenu.setVisible(true);
//    
//    //TODO: change special move handling
//    int i = Integer.parseInt(JOptionPane.showInputDialog("Which enemy?"));  
//	JOptionPane.showMessageDialog(null,"attacking now");
//	battle.attack(0,i);
//    battle.attack(0,i);
//}//GEN-LAST:event_bBladeActionPerformed
//
//private void specialAttackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specialAttackActionPerformed
//    mainMenu.setVisible(false);
//    specialMenu.setVisible(true);
//}//GEN-LAST:event_specialAttackActionPerformed
//
//private void specialBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specialBackActionPerformed
//    specialMenu.setVisible(false);
//    mainMenu.setVisible(true);
//}//GEN-LAST:event_specialBackActionPerformed

    /**
     * @param args the command line arguments
     */
    private void setup()
    {
        mainMenu.setVisible(false);
        specialMenu.setVisible(false);
    }
    private void update()
    {
    	//TODO: for loop through entities and place stats for each one in GUI
    	
        //Base entity = entities.get(0);
      //  hpFeildPlayer.setText(String.valueOf(entity.getHp()));
        //tpFeild.setText(String.valueOf(entity.getTp()));
       // Base grunt = entities.get(1);
      //  hpFeildEnemy.setText(String.valueOf(grunt.getHp()));
      //  grunt = entities.get(2);
      //  test.setText(String.valueOf(grunt.getHp()));
        
    }
    
    public void showMenu(JLayeredPane menu){
    	//TODO: player specific menus
    	mainMenu.setVisible(true);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBlade;
    private javax.swing.JButton basicAttack;
    private javax.swing.JTextField hpFeildEnemy;
    private javax.swing.JTextField hpFeildPlayer;
    private javax.swing.JLabel hpLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLayeredPane mainMenu;
    private javax.swing.JLabel name;
    private javax.swing.JButton specialAttack;
    private javax.swing.JButton specialBack;
    private javax.swing.JLayeredPane specialMenu;
    private javax.swing.JTextField test;
    private javax.swing.JTextField tpFeild;
    private javax.swing.JLabel tpLabel;
    // End of variables declaration//GEN-END:variables
}
